Adapted a test case so that it catches this bug:
java.lang.ClassCastException: at.silverstrike.pcc.impl.tj3bookingsparser.DefaultBookingsFile2BookingsFactory cannot be cast to co.altruix.pcc.api.booking2calendarevententry.Booking2CalendarEventEntryConverterFactory
	at co.altruix.pcc.impl.exporter2googlecalendar.DefaultExporter2GoogleCalendar.exportBookings(DefaultExporter2GoogleCalendar.java:130) ~[pcc-worker-1.9-jar-with-dependencies.jar:na]
	at co.altruix.pcc.impl.exporter2googlecalendar.DefaultExporter2GoogleCalendar.run(DefaultExporter2GoogleCalendar.java:116) ~[pcc-worker-1.9-jar-with-dependencies.jar:na]
	at co.altruix.pcc.api.schedulingrequestmessageprocessor.AbstractSchedulingRequestMessageProcessor.exportDataToGoogleCalendar(AbstractSchedulingRequestMessageProcessor.java:135) ~[pcc-worker-1.9-jar-with-dependencies.jar:na]
	at co.altruix.pcc.impl.immediatereschedulingrequestprocessor.DefaultImmediateSchedulingRequestMessageProcessor.run(DefaultImmediateSchedulingRequestMessageProcessor.java:60) ~[pcc-worker-1.9-jar-with-dependencies.jar:na]
	at co.altruix.pcc.impl.dispatcher.DefaultDispatcher.processObjectMessage(DefaultDispatcher.java:102) ~[pcc-worker-1.9-jar-with-dependencies.jar:na]
	at co.altruix.pcc.impl.dispatcher.DefaultDispatcher.run(DefaultDispatcher.java:54) ~[pcc-worker-1.9-jar-with-dependencies.jar:na]
	at co.altruix.pcc.PccWorkerApp.run(PccWorkerApp.java:100) ~[pcc-worker-1.9-jar-with-dependencies.jar:na]
	at co.altruix.pcc.PccWorkerApp.main(PccWorkerApp.java:220) ~[pcc-worker-1.9-jar-with-dependencies.jar:na]